spring.datasource.url=postgresql://postgres:@localhost/divumdb
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

hibernate.connection.url=postgresql://postgres:@localhost/divum
hibernate.connection.username=postgres
hibernate.connection.password=

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true